//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core.Data.Structure
{
	using Core.Data;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IDeviceRepository 
	{
		DeviceEntity GetDevice(int id);

		void AddDevice(DeviceEntity device);

		void DeleteDevice(DeviceEntity device);

		IEnumerable<DeviceEntity> GetAll();

		DeviceEntity GetDevice(string deviceId);

		string GetImagePath(int id);

		DeviceEntity GetImagePath(string deviceId);

		void UpdateDevice(DeviceEntity device);

	}
}

