//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core.Lib.Structure
{
	using Core.Data;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IMenuModule 
	{
		void Register(BaseMenuManager menuManager);

		void SaveImages(IEnumerable<ImageEntity> images);

	}
}

