//  Copyright (c) 2016 Thomas Ohms
//
//  This file is part of PictureShare.
//
//  Get the original code from https://thomas4u.github.io/PictureShare/
//
//  PictureShare is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  PictureShare is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with PictureShare.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace PictureShare.Core.Data.Structure
{
	using PictureShare.Core.Data;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseDeviceRepository : IDeviceRepository
	{
		protected IEnumerable<DeviceEntity> Devices;

		public abstract DeviceEntity GetDevice(int id);

		public abstract void AddDevice(DeviceEntity device);

		public abstract void DeleteDevice(DeviceEntity device);

		public abstract IEnumerable<DeviceEntity> GetAll();

		public abstract DeviceEntity GetDevice(string deviceId);

		public abstract string GetImagePath(int id);

		public abstract string GetImagePath(string deviceId);

		public abstract void UpdateDevice(DeviceEntity device);

		public abstract bool SaveChanges();

	}
}

