//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace PictureShare.Core.Data.Structure
{
	using PictureShare.Core.Data;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseDeviceRepository : IDeviceRepository
	{
		protected IEnumerable<DeviceEntity> Devices;

		public abstract DeviceEntity GetDevice(int id);

		public abstract void AddDevice(DeviceEntity device);

		public abstract void DeleteDevice(DeviceEntity device);

		public abstract IEnumerable<DeviceEntity> GetAll();

		public abstract DeviceEntity GetDevice(string deviceId);

		public abstract string GetImagePath(int id);

		public abstract string GetImagePath(string deviceId);

		public abstract void UpdateDevice(DeviceEntity device);

		public abstract bool SaveChanges();

	}
}

