//  Copyright (c) 2016 Thomas Ohms
//
//  This file is part of PictureShare.
//
//  Get the original code from https://thomas4u.github.io/PictureShare/
//
//  PictureShare is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  PictureShare is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with PictureShare.  If not, see <http://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace PictureShare.Core.Lib.Structure
{
	using PictureShare.Core.Data;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseMenuManager : IMenuManager
	{
		public event EventHandler OnMenuCanceled;

		public event EventHandler OnMenuConfirmed;

		public virtual ModuleEntity SelectedModule
		{
			get;
			set;
		}

		public virtual DeviceEntity ConnectedDevice
		{
			get;
			set;
		}

		public event EventHandler OnPicsCanceled;

		public event EventHandler OnPicsConfirmed;

		public virtual IEnumerable<ImageEntity> Images
		{
			get;
			set;
		}

		protected virtual IEnumerable<ModuleEntity> AvailableModules
		{
			get;
			set;
		}

		protected abstract void RegisterModules();

		public abstract void ShowMenu();

		public abstract void ShowPicsSelectionMenu();

		protected abstract void SaveImages();

		protected abstract void DeleteImages();

		protected abstract void LoadPicsFromDevice();

	}
}

