//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace PictureShare.Core.Lib.Structure
{
	using PictureShare.Core.Data;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseDeviceManager : IDeviceManager
	{
		protected string DriveLetter;

		public abstract DeviceEntity GetDevice(string deviceId);

		protected abstract string FindImageFolder();

		protected abstract bool AskAutoPathCorrect(string path);

		protected abstract string AskForFolder();

		protected abstract void AddDevice(DeviceEntity device);

		public BaseDeviceManager(string driveLetter)
		{
		}

	}
}

