//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace PictureShare.Core.Lib.Structure
{
	using PictureShare.Core.Data;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class BaseMenuManager : IMenuManager
	{
		public event EventHandler OnMenuCanceled;

		public event EventHandler OnMenuConfirmed;

		public virtual ModuleEntity SelectedModule
		{
			get;
			set;
		}

		public virtual DeviceEntity ConnectedDevice
		{
			get;
			set;
		}

		public event EventHandler OnPicsCanceled;

		public event EventHandler OnPicsConfirmed;

		public virtual IEnumerable<ImageEntity> Images
		{
			get;
			set;
		}

		protected virtual IEnumerable<ModuleEntity> AvailableModules
		{
			get;
			set;
		}

		protected abstract void RegisterModules();

		public abstract void ShowMenu();

		public abstract void ShowPicsSelectionMenu();

		protected abstract void SaveImages();

		protected abstract void DeleteImages();

		protected abstract void LoadPicsFromDevice();

	}
}

