//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core.Data
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public struct ImageEntity
	{
		public string Path
		{
			get;
			set;
		}

		public object Name
		{
			get;
			set;
		}

		public string Album
		{
			get;
			set;
		}

	}
}

