//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace PictureShare.Core.Data
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public struct DeviceEntity
	{
		public string ImageFolder
		{
			get;
			set;
		}

		public string DeviceId
		{
			get;
			set;
		}

		public int DeviceEntityId
		{
			get;
			set;
		}

	}
}

